#This layer.conf file defines settings for the meta-aesd layer

# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}" 
# Bitbake search path
# ${LAYERDIR} expands to meta-aesd/

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-aesd"
BBFILE_PATTERN_meta-aesd = "^${LAYERDIR}/"
# The BBFILE_PATTERN ensures that only files inside meta-aesd/ are considered part of this layer.

BBFILE_PRIORITY_meta-aesd = "6"
# Higher numbers mean higher priority when resolving conflicting recipes. Since it's 6, it will override lower-priority layers if needed.

LAYERDEPENDS_meta-aesd = "core"  
# meta-aesd layer depends on the core layer

LAYERSERIES_COMPAT_meta-aesd = "hardknott kirkstone" 
# Ensures this layer is compatible with Yocto versions hardknott and kirkstone
